version: '3.4'

networks:
  default:
    driver: bridge
services:
  api:
    build: .
    networks:
      - default
    volumes:
      - ./app/:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

  front:
    build:
      context: front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    depends_on:
      - api